In [1]:
from fastai.vision import *
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
img_path = Path("/home/sloth/Desktop/animeface/animeface-2009/animeface-ruby/out-3")

In [3]:
data_source = ImageList.from_folder(img_path).split_none().label_from_folder()

In [4]:
data_source

LabelLists;

Train: LabelList (48666 items)
x: ImageList
Image (3, 89, 89),Image (3, 116, 116),Image (3, 97, 97),Image (3, 116, 116),Image (3, 128, 128)
y: CategoryList
out-3,out-3,out-3,out-3,out-3
Path: /home/sloth/Desktop/animeface/animeface-2009/animeface-ruby/out-3;

Valid: LabelList (0 items)
x: ImageList

y: CategoryList

Path: /home/sloth/Desktop/animeface/animeface-2009/animeface-ruby/out-3;

Test: None

In [5]:
tmsf = get_transforms()

In [6]:
data = data_source.transform(tmsf, size=128).databunch(bs=64).normalize(imagenet_stats)

In [7]:
dataloader = data.train_dl.new(shuffle=False)

In [8]:
learner= cnn_learner(data, models.resnet152)

In [9]:
learner.model = torch.nn.DataParallel(learner.model)
model = learner.model.module

In [10]:
for x, y in model.named_modules():
    print(x, y)

 Sequential(
  (0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequential(
          (0): Conv2d(64, 25

In [12]:
# hook code based on https://towardsdatascience.com/similar-images-recommendations-using-fastai-and-annoy-16d6ceb3b809 

class Hook():
    "Create a hook on `m` with `hook_func`."
    def __init__(self, m:nn.Module, hook_func:HookFunc, is_forward:bool=True, detach:bool=True):
        self.hook_func,self.detach,self.stored = hook_func,detach,None
        f = m.register_forward_hook if is_forward else m.register_backward_hook
        self.hook = f(self.hook_fn)
        self.removed = False

    def hook_fn(self, module:nn.Module, input:Tensors, output:Tensors):
        "Applies `hook_func` to `module`, `input`, `output`."
        if self.detach:
            input  = (o.detach() for o in input ) if is_listy(input ) else input.detach()
            output = (o.detach() for o in output) if is_listy(output) else output.detach()
        self.stored = self.hook_func(module, input, output)

    def remove(self):
        "Remove the hook from the model."
        if not self.removed:
            self.hook.remove()
            self.removed=True

    def __enter__(self, *args): return self
    def __exit__(self, *args): self.remove()
        
def get_output(module, input_value, output):
    return output.flatten(1)

def get_input(module, input_value, output):
    return list(input_value)[0]

def get_named_module_from_model(model, name):
    for n, m in model.named_modules():
        if n == name:
            return m
    return None

In [13]:
out_layer = get_named_module_from_model(model, "1.4")

In [32]:
img_vecs = {}

with Hook(out_layer, get_output, True, True) as hook:
    start = time.time()
    for i, (xb, yb) in enumerate(dataloader):
        bs = xb.shape[0]
        img_ids = dataloader.items[i*bs: (i+1)*bs]
        result = model.eval()(xb)
        img_reprs = hook.stored.cpu().numpy()
        print(img_reprs)
        img_reprs = img_reprs.reshape(bs, -1)
        for img_id, img_repr in zip(img_ids, img_reprs):
            img_repr_map[img_id] = img_repr

[[0.       0.       0.       0.       ... 0.970437 1.730672 1.717203 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       1.695651 0.      ]
 [0.       0.       0.       0.       ... 1.868422 0.       3.769852 0.      ]
 [0.       0.       0.       0.       ... 1.085263 0.       1.282947 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.254855 0.78448  1.682872 0.      ]
 [0.275125 0.       0.       0.       ... 0.       2.156593 4.049745 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       4.236913 0.      ]
 [0.       0.       0.       0.       ... 0.07265  0.815412 3.332256 0.      ]]
[[0.       0.       0.       0.       ... 1.075221 2.22124  3.46255  0.      ]
 [0.       0.       0.       0.       ... 0.552649 0.689899 3.265951 0.      ]
 [0.       0.       0.       0.851781 ... 0.       2.398453 4.750698 0.      ]
 [0.       0.       0.491939 1.586208 ... 3.271238 0.       4.259107 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.       0.922217 2.184268 0.      ]
 [0.       0.       0.       0.       ... 2.599903 0.       2.286766 0.      ]
 [0.       0.       0.       0.       ... 1.484385 0.       2.320165 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.34348  0.      ]
 ...
 [0.       0.       0.       0.       ... 0.959192 1.838321 4.725713 0.      ]
 [0.       0.       0.       1.055732 ... 0.       1.661766 2.602375 0.      ]
 [0.       0.       0.       0.504984 ... 2.812556 0.559874 5.327992 0.      ]
 [0.       0.       0.       0.       ... 0.       0.604874 4.514921 0.      ]]
[[0.       0.       0.       0.       ... 0.451633 2.129893 5.8126   0.      ]
 [0.       0.       0.010442 0.       ... 0.       0.       2.955616 0.      ]
 [0.       0.       0.       0.       ... 0.356734 0.32218  3.153028 0.      ]
 [0.       0.       0.       0.       ... 0.029582 0.324316 3.761045 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.44376  ... 1.426862 0.       2.463756 0.      ]
 [0.       0.       0.       0.       ... 0.743965 0.840572 1.18986  0.      ]
 [0.       0.       0.       0.       ... 0.21757  1.040758 2.38822  0.      ]
 [0.       0.       0.       0.       ... 0.443917 1.787766 2.844798 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.715864 0.276773 0.847882 0.      ]
 [0.       0.       0.       0.       ... 1.261164 0.       4.637238 0.      ]
 [0.       0.       0.       0.       ... 1.867413 0.52096  0.080795 0.      ]
 [0.       0.       0.       0.       ... 1.398966 0.126944 1.640263 0.      ]]
[[0.       0.       0.       0.       ... 0.441981 0.       2.416637 0.      ]
 [0.       0.       0.       0.       ... 1.27905  1.019815 1.811253 0.      ]
 [0.       0.       0.       0.       ... 0.405544 1.778719 3.93022  0.      ]
 [0.       0.       0.       0.       ... 0.109356 0.       0.       0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.393227 1.123078 4.123558 0.      ]
 [0.       0.       0.       0.       ... 2.386974 0.308445 4.257157 0.      ]
 [0.       0.       0.       0.       ... 1.909734 0.542668 1.964134 0.      ]
 [0.       0.       0.       0.       ... 0.492091 1.582109 2.807994 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.829901 0.       1.303923 0.      ]
 [0.       0.       0.       0.       ... 0.       0.400806 2.147327 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       0.       0.      ]
 [0.       0.       0.       0.       ... 1.600439 0.       1.16254  0.      ]]
[[0.       0.       0.       0.       ... 0.       2.383992 3.779638 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       2.228703 0.      ]
 [0.       0.       0.       0.       ... 0.693284 0.608203 1.193192 0.      ]
 [0.       0.075015 0.       0.       ... 1.505881 0.       1.769691 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.296485 0.       2.235747 0.      ]
 [0.       0.       0.       0.       ... 1.710504 0.777153 2.13129  0.      ]
 [0.       0.       0.       0.       ... 2.723057 0.       1.430356 0.      ]
 [0.       0.       0.       0.       ... 0.891449 0.       2.268249 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.551935 0.508494 1.411396 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.048881 0.      ]
 [0.       0.       0.       0.       ... 0.373673 0.660143 2.862944 0.      ]
 [0.       0.       0.       0.       ... 0.       0.466825 3.862116 0.      ]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.106488e+00 3.889148e-01 3.015391e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.910463e+00 7.795215e-02 1.758587e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 3.775835e-03 0.000000e+00 1.626261e+00 0.000000e+00]
 [0.000000e+00 3.895307e-02 0

[[0.000000e+00 0.000000e+00 3.306538e-03 0.000000e+00 ... 5.123572e-01 4.431598e-01 3.835564e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 0.000000e+00 2.760625e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 6.147814e-01 0.000000e+00 ... 1.327323e+00 6.622138e-01 4.852356e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 9.251338e-01 2.426782e+00 0.000000e+00]
 ...
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 2.421508e+00 0.000000e+00 2.574778e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 6.743861e-01 0.000000e+00 ... 2.348455e+00 2.832272e+00 3.708528e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 7.394344e-02 4.075123e-01 ... 1.186026e+00 7.588108e-01 4.185705e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 2.812775e+00 4.020531e-01 3.368976e+00 0.000000e+00]]
[[0.       0.       0.       0.       ... 0.502086 1.910158 2.843642 0.      ]
 [0.       0.       1.24692

[[0.       0.       0.       0.       ... 1.360408 0.       1.300985 0.      ]
 [0.       0.       0.       0.       ... 1.397636 0.       2.066759 0.      ]
 [0.       0.       0.       0.       ... 1.249675 0.       2.130056 0.      ]
 [0.       0.       0.       0.       ... 0.332389 1.222558 1.470235 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.       0.       2.171291 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       0.       0.      ]
 [0.       0.       0.790793 0.       ... 0.269637 0.       5.290091 0.      ]
 [0.       0.       0.011064 0.       ... 0.       0.       4.924667 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.217506 3.433812 0.      ]
 [0.       0.       0.       0.       ... 1.035171 0.       1.603561 0.      ]
 [0.       0.       0.       0.       ... 0.       0.043652 1.501064 0.      ]
 [0.       0.       0.       0.       ... 0.978214 0.       3.045675 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.       0.       2.208989 0.      ]
 [0.       0.       0.       0.       ... 0.050713 0.36568  0.55386  0.      ]
 [0.       0.       0.       0.       ... 0.948852 1.719162 3.819009 0.      ]
 [0.       0.       0.       0.       ... 0.936996 0.578835 1.904821 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.425272 0.762081 2.443685 0.      ]
 [0.       0.       0.       0.       ... 1.083644 0.867516 3.465213 0.      ]
 [0.       0.       0.262129 0.       ... 0.       0.74468  3.097741 0.      ]
 [0.       0.       0.       0.       ... 1.975521 0.847452 3.019386 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.568708 3.554119 0.      ]
 [0.       0.       0.       0.       ... 1.50764  0.60785  2.277456 0.      ]
 [0.       0.       0.       0.       ... 0.       0.510219 2.482736 0.      ]
 [0.       0.       0.       0.       ... 0.247283 0.       1.904431 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.193105 0.       4.239931 0.      ]
 [0.       0.       0.       0.       ... 0.369723 0.       0.200288 0.      ]
 [0.       0.       0.       0.407566 ... 0.47694  1.215147 1.680284 0.      ]
 [0.       0.       0.       0.       ... 0.58601  0.       3.085164 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.622671 1.419373 1.967424 0.      ]
 [0.       0.       0.       0.       ... 3.065279 2.09625  3.322477 0.      ]
 [0.       0.       0.       0.       ... 0.       0.241989 1.027506 0.      ]
 [0.       0.       0.       0.       ... 0.686446 0.       2.53971  0.      ]]
[[0.       0.       0.       0.       ... 0.020016 0.       3.770095 0.      ]
 [0.       0.       0.       0.       ... 1.187095 0.       1.66753  0.      ]
 [0.       0.       0.       0.       ... 1.264553 2.12423  1.109604 0.      ]
 [0.       0.       0.       0.       ... 1.204319 0.801887 1.638102 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.27309  0.       2.753724 0.      ]
 [0.       0.       0.06027  0.       ... 0.       1.892504 4.186882 0.      ]
 [0.       0.       0.       0.       ... 1.742898 0.876189 0.43779  0.      ]
 [0.       0.       0.320707 0.       ... 0.304674 0.844403 2.171712 0.      ]
 ...
 [0.       0.       0.       0.       ... 2.446918 1.035582 4.146983 0.      ]
 [0.       0.       0.       0.       ... 0.932302 1.084485 1.970517 0.      ]
 [0.       0.       0.       0.       ... 1.244541 0.324432 3.474242 0.      ]
 [0.       0.       0.       0.       ... 1.062113 0.       4.091496 0.      ]]
[[0.       0.       0.       0.       ... 0.750981 0.       2.530617 0.      ]
 [0.       0.       0.       0.       ... 0.       0.116553 1.411461 0.      ]
 [0.       0.       0.103855 0.55775  ... 2.116255 0.145747 4.097232 0.      ]
 [0.       0.       0.       0.       ... 0.017444 0.783735 2.535267 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.197277 ... 0.827534 1.140085 5.045446 0.      ]
 [0.       0.       0.       0.       ... 0.948034 0.131725 4.200217 0.      ]
 [0.       0.       0.       0.       ... 1.99511  0.       3.417597 0.      ]
 [0.       0.       0.       0.652636 ... 0.       1.045711 4.401869 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.473982 1.024643 3.107838 0.      ]
 [0.       0.       0.       0.       ... 1.97337  0.435187 2.210404 0.      ]
 [0.       0.       0.       0.       ... 0.654477 0.       5.700364 0.      ]
 [0.       0.       0.       0.       ... 1.505197 0.127377 3.137812 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.       5.669794 0.      ]
 [0.       0.       0.       0.       ... 1.288416 0.       1.544071 0.      ]
 [0.       0.       0.       0.       ... 1.136942 0.       1.907807 0.      ]
 [0.       0.       0.       0.       ... 0.574781 1.153692 4.735225 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.328023 0.       ... 1.204589 0.       1.572185 0.      ]
 [0.       0.       0.       0.112522 ... 1.268106 0.936033 2.064437 0.      ]
 [0.       0.       0.       0.       ... 0.607232 0.493164 2.348754 0.      ]
 [0.       0.       0.       0.       ... 0.448088 0.976267 2.453346 0.      ]
 ...
 [0.       0.       1.760025 0.       ... 0.       2.145612 5.010646 0.      ]
 [0.       0.       0.       0.       ... 1.29486  0.       5.326221 0.      ]
 [0.       0.       0.       0.       ... 0.68299  0.       2.15362  0.      ]
 [0.       0.       0.       0.       ... 2.01898  1.869882 2.729189 0.      ]]
[[0.       0.       0.       0.       ... 1.648263 0.078689 3.65293  0.      ]
 [0.       0.       0.578398 0.       ... 0.       0.       3.44945  0.      ]
 [0.       0.       0.894124 0.       ... 0.289025 0.894496 4.630306 0.      ]
 [0.       0.       0.       0.       ... 2.476529 0.       3.084534 0.      ]
 ...
 [0.       0.       0.       0.58179  ...

[[0.       0.       0.       0.       ... 1.239302 0.72675  2.355422 0.      ]
 [0.       0.       0.       0.       ... 0.052205 0.889921 1.189143 0.      ]
 [0.       0.       0.       0.       ... 0.       1.05372  4.68363  0.      ]
 [0.       0.       0.       0.       ... 0.       1.100581 2.040096 0.      ]
 ...
 [0.       0.       0.452997 0.       ... 3.136498 1.079066 3.375046 0.      ]
 [0.       0.       0.       0.       ... 0.928125 0.       4.916188 0.      ]
 [0.       0.       0.       1.60766  ... 0.047588 0.       2.832372 0.      ]
 [0.       0.       0.       0.       ... 1.371329 1.195391 3.993165 0.      ]]
[[0.       0.       0.086543 0.       ... 0.       1.39332  3.285461 0.      ]
 [0.       0.       0.       0.017363 ... 0.952329 0.641929 2.842461 0.      ]
 [0.       0.       0.       1.712205 ... 0.520497 2.144182 3.49705  0.      ]
 [0.       0.       0.       0.       ... 1.493624 1.140447 2.828886 0.      ]
 ...
 [0.       0.       0.687836 0.       ...

[[0.       0.       0.213302 0.       ... 1.849195 0.455308 4.296942 0.      ]
 [0.       0.       0.       0.       ... 0.       0.644319 3.961519 0.      ]
 [0.       0.       1.025301 0.       ... 1.416756 1.046357 6.1736   0.      ]
 [0.       0.       0.       0.       ... 0.       0.458843 2.360414 0.      ]
 ...
 [0.       0.       0.       0.790687 ... 1.975361 1.180346 3.075702 0.      ]
 [0.       0.       0.       0.       ... 1.799453 0.       2.062154 0.      ]
 [0.       0.       0.       0.       ... 1.185561 0.418487 3.030525 0.      ]
 [0.       0.       0.       1.139843 ... 0.017679 1.881968 3.303632 0.      ]]
[[0.       0.       0.       0.       ... 0.902355 1.953557 2.512514 0.      ]
 [0.       0.       0.       0.       ... 1.53707  0.       2.298963 0.      ]
 [0.       0.       0.       0.       ... 0.790822 1.087744 3.248324 0.      ]
 [0.       0.       0.       0.       ... 1.09836  0.981033 3.059874 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.       0.381115 4.264371 0.      ]
 [0.       0.       0.       0.065743 ... 1.21355  0.       6.012072 0.      ]
 [0.       0.       0.       0.       ... 0.       1.211624 2.875795 0.      ]
 [0.       0.       0.       0.       ... 0.670447 1.084894 1.783466 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.768938 0.       2.455965 0.      ]
 [0.       0.       0.       0.       ... 0.894078 0.       3.460093 0.      ]
 [0.       0.       1.702464 0.439628 ... 1.067777 1.889654 6.339024 0.      ]
 [0.       0.       0.       0.       ... 0.030477 0.       1.721524 0.      ]]
[[0.       0.       0.       0.       ... 1.46722  0.       1.591611 0.      ]
 [0.       0.       0.       0.       ... 0.       1.18637  2.089176 0.      ]
 [0.       0.       0.869192 0.284069 ... 0.       0.       5.218239 0.      ]
 [0.       0.       0.       0.       ... 0.484071 0.007754 2.628386 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.685177 1.966859 7.376664 0.      ]
 [0.       0.       0.       0.       ... 1.451728 0.243052 4.403066 0.      ]
 [0.       0.       0.       0.       ... 1.067306 1.555532 4.995785 0.      ]
 [0.       0.       0.       0.       ... 1.959316 0.       2.543551 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.205294 0.       1.208603 0.      ]
 [0.       0.       0.       0.       ... 1.387245 0.140572 2.327375 0.      ]
 [0.       0.       0.       0.       ... 0.750414 1.953078 2.889771 0.      ]
 [0.       0.       0.       0.230627 ... 0.491322 1.004027 2.637492 0.      ]]
[[0.       0.       0.       0.       ... 1.224921 1.200949 2.909662 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       4.83675  0.      ]
 [0.       0.       0.       0.       ... 0.       0.       5.825622 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       1.842939 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.290945 0.       3.63112  0.      ]
 [0.       0.       0.       0.       ... 0.133035 0.949495 1.822064 0.      ]
 [0.       0.       0.       0.       ... 1.98962  0.       0.56707  0.      ]
 [0.       0.       0.       0.031288 ... 0.461166 0.457135 3.339772 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.       0.       2.471082 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.68666  0.      ]
 [0.       0.       0.       0.       ... 0.       1.460691 3.349845 0.      ]
 [0.       0.       0.833675 0.935667 ... 0.513954 2.497636 4.997574 0.      ]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 7.531469e-01 1.039381e+00 3.637019e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.464170e+00 2.036795e+00 1.967818e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 2.061938e-01 6.713715e-01 2.369968e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0

[[0.       0.       0.       0.       ... 1.489592 0.       1.64517  0.      ]
 [0.       0.       0.       1.212758 ... 0.438784 3.517646 7.806261 0.      ]
 [0.       0.       0.872505 0.       ... 1.326709 0.228762 1.873953 0.      ]
 [0.       0.       0.       0.       ... 0.       0.69805  2.026414 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.894474 0.       0.830425 0.      ]
 [0.       0.       0.       0.       ... 0.564609 0.       3.249243 0.      ]
 [0.       0.       0.       0.       ... 0.63284  0.       0.693758 0.      ]
 [0.       0.       0.       0.       ... 1.717717 0.774962 0.315984 0.      ]]
[[0.       0.       0.       0.       ... 1.120861 0.       5.246689 0.      ]
 [0.       0.       0.       0.       ... 0.363438 1.100005 2.087977 0.      ]
 [0.       0.       0.       0.       ... 1.021478 0.       4.279976 0.      ]
 [0.       0.       0.       0.92     ... 0.       2.336565 6.100923 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.802251 0.051749 2.515232 0.      ]
 [0.       0.       0.       0.       ... 0.379848 0.038129 1.305035 0.      ]
 [0.       0.       0.       0.       ... 1.468455 0.272625 2.578946 0.      ]
 [0.       0.       0.       0.       ... 1.816016 0.604256 1.461348 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.235192 0.       0.492148 0.      ]
 [0.       0.       0.       0.       ... 1.204401 0.882497 2.904613 0.      ]
 [0.       0.       0.       0.363339 ... 0.       0.       2.249869 0.      ]
 [0.       0.       0.       0.       ... 0.499215 1.165839 1.613505 0.      ]]
[[0.       0.       0.       0.       ... 0.       1.05855  6.576276 0.04685 ]
 [0.       0.       0.       0.       ... 2.709957 0.952791 3.422238 0.      ]
 [0.       0.       0.081425 0.       ... 1.002116 0.       2.069746 0.      ]
 [0.       0.       0.       0.       ... 1.150193 0.78912  3.111274 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.709616 1.393294 2.760774 0.      ]
 [0.       0.       0.324519 0.       ... 2.228925 1.280446 5.753278 0.      ]
 [0.       0.       0.       0.       ... 1.265805 0.       0.862782 0.      ]
 [0.       0.       0.       0.       ... 1.140447 0.       0.705757 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.337371 0.426175 2.22322  0.      ]
 [0.       0.       0.       0.       ... 0.       1.061692 4.142209 0.      ]
 [0.       0.       0.       0.       ... 0.484574 0.       3.141001 0.      ]
 [0.       0.       0.       0.607673 ... 1.850311 0.360189 1.35258  0.      ]]
[[0.       0.       0.       0.       ... 0.       1.116378 4.716238 0.      ]
 [0.       0.       0.       0.       ... 0.804295 1.059212 3.036647 0.      ]
 [0.       0.       0.       0.216135 ... 1.483112 0.       2.228883 0.      ]
 [0.       0.       0.       0.       ... 2.448178 0.       1.441138 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.       0.212423 4.006346 0.      ]
 [0.       0.       0.       0.       ... 0.675532 1.054798 3.173012 0.      ]
 [0.       0.       0.       0.       ... 0.502953 1.910534 4.640534 0.      ]
 [0.       0.       0.       0.       ... 2.049102 0.630083 4.067498 0.      ]
 ...
 [0.       0.       0.       0.21177  ... 2.274151 0.608863 3.460451 0.      ]
 [0.       0.       0.       0.       ... 3.28035  0.663437 4.221694 0.      ]
 [0.       0.       0.11804  0.       ... 2.433257 0.573762 2.429592 0.      ]
 [0.       0.       0.       0.       ... 0.       4.336364 4.525188 0.      ]]
[[0.       0.       0.       0.       ... 1.438479 0.134047 1.941746 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       4.048824 0.      ]
 [0.       0.       0.       0.       ... 0.310017 0.693516 2.303381 0.      ]
 [0.       0.       0.       0.       ... 0.       2.008034 6.811236 0.      ]
 ...
 [0.       0.       0.       0.417356 ...

[[0.       0.       0.       0.177705 ... 0.380534 1.569365 1.55985  0.      ]
 [0.       0.       0.       0.       ... 0.811485 0.993252 3.303456 0.      ]
 [0.       0.       0.       0.       ... 0.       0.526972 0.877497 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       1.734835 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.663301 1.252449 1.859984 0.      ]
 [0.       0.517281 0.       0.       ... 1.590453 1.516968 4.716201 0.      ]
 [0.       0.       0.       0.       ... 1.763003 1.424743 2.864044 0.      ]
 [0.       0.       0.       0.       ... 0.96604  0.       1.243688 0.      ]]
[[0.       0.       0.756188 0.       ... 0.926863 0.18381  3.743787 0.      ]
 [0.       0.       0.       0.       ... 0.820876 0.63594  3.134377 0.      ]
 [0.       0.       0.178342 0.       ... 0.       1.202263 3.154795 0.      ]
 [0.       0.       0.624552 0.       ... 0.       0.       3.118469 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.000000e+00 0.000000e+00 4.139730e-01 0.000000e+00 ... 1.425859e+00 4.801277e-01 2.625501e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.567832e+00 4.248798e-03 4.195899e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 2.314583e+00 0.000000e+00 2.088194e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 0.000000e+00 8.207865e-01 0.000000e+00]
 ...
 [0.000000e+00 0.000000e+00 1.377676e+00 0.000000e+00 ... 4.846556e-01 4.604805e+00 2.666620e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 3.881150e+00 2.110546e+00 1.037620e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 7.160755e-01 0.000000e+00 4.048446e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 4.541953e-01 0.000000e+00 2.154908e+00 0.000000e+00]]
[[0.       0.       0.       0.       ... 0.275594 1.268229 1.037067 0.      ]
 [0.       0.       0.     

[[0.       0.       0.       0.       ... 0.778239 0.       1.47857  0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.439073 0.      ]
 [0.       0.       0.       0.       ... 1.420859 0.785275 4.928873 0.      ]
 [0.       0.       0.       0.005427 ... 0.       0.       2.476547 0.      ]
 ...
 [0.       0.       0.       0.37998  ... 0.237354 0.       2.110289 0.      ]
 [0.       0.       0.       0.       ... 0.466492 0.       1.833656 0.      ]
 [0.       0.       0.       0.       ... 0.34065  0.778477 1.910657 0.      ]
 [0.       0.       0.       0.       ... 2.139988 0.       3.730497 0.      ]]
[[0.       0.       0.       0.       ... 0.173025 0.       1.789905 0.      ]
 [0.       0.       0.       0.       ... 0.       0.376225 3.370589 0.      ]
 [0.       0.       0.       0.       ... 0.       2.763052 7.518175 0.      ]
 [0.       0.       0.       0.       ... 0.937756 0.74647  2.609379 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.377108 0.51792  2.330469 0.      ]
 [0.       0.       0.       0.       ... 1.832272 0.       3.017057 0.      ]
 [0.       0.       0.       0.557772 ... 0.       1.635515 5.437965 0.      ]
 [0.       0.       0.       0.       ... 0.959192 1.578873 3.473334 0.      ]
 ...
 [0.       0.       0.       1.768649 ... 0.       0.       2.421809 0.      ]
 [0.       0.       0.       0.       ... 0.408544 1.734312 2.954461 0.      ]
 [0.       0.       0.       0.       ... 0.868807 0.       0.775722 0.      ]
 [0.       0.       0.       0.       ... 0.897404 0.967616 3.482601 0.      ]]
[[0.       0.       0.       0.       ... 0.820521 0.       2.155761 0.      ]
 [0.       0.       0.       0.       ... 0.       0.221846 1.816853 0.      ]
 [0.       0.       0.       0.       ... 0.707713 1.104021 2.95949  0.      ]
 [0.       0.       1.352218 0.       ... 2.554371 2.147231 5.732783 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.573224 0.       4.513283 0.      ]
 [0.       0.       0.       0.       ... 0.577158 2.296615 2.177011 0.      ]
 [0.       0.       0.       0.       ... 1.303054 0.243678 2.323272 0.      ]
 [0.       0.       0.       0.       ... 0.089268 0.110564 2.711537 0.      ]
 ...
 [0.       0.       0.       0.971084 ... 2.791619 1.773553 3.432516 0.      ]
 [0.       0.       0.       0.       ... 0.204328 0.011465 1.221346 0.      ]
 [0.       0.       0.       0.       ... 1.455138 0.389333 2.846085 0.      ]
 [0.       0.       0.       0.       ... 1.227036 0.226593 2.001621 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.801033 5.900712 0.      ]
 [0.       0.       0.       0.       ... 1.93015  1.018319 3.533779 0.      ]
 [0.       0.       0.       0.       ... 1.463703 0.       3.20711  0.      ]
 [0.       0.       0.       0.       ... 0.       1.866067 5.866353 0.      ]
 ...
 [0.       0.       0.       0.082556 ...

[[0.       0.       0.       1.207643 ... 1.004673 0.       0.       0.      ]
 [0.       0.       0.       0.       ... 0.       0.       2.86021  0.      ]
 [0.       0.       0.       0.       ... 1.183254 0.490749 2.497084 0.      ]
 [0.       0.       0.       0.       ... 1.588561 0.616169 0.849562 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.793777 1.157054 1.484747 0.      ]
 [0.       0.       0.329223 0.       ... 0.       0.136336 3.171295 0.      ]
 [0.       0.       0.       0.       ... 0.051656 1.476569 4.782252 0.      ]
 [0.       0.       0.       0.       ... 1.697673 0.526488 1.307818 0.      ]]
[[0.       0.       0.       0.314359 ... 1.309717 0.       3.142745 0.      ]
 [0.       0.       0.       0.       ... 0.439756 0.061374 0.725954 0.      ]
 [0.       0.       0.       0.       ... 1.52318  0.       2.685803 0.      ]
 [0.       0.       0.       0.       ... 2.009525 0.       1.611722 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.584095 ... 1.779512 0.195798 4.961565 0.      ]
 [0.       0.       0.       0.       ... 0.450648 0.       2.016825 0.      ]
 [0.       0.       0.       0.       ... 0.962533 2.4184   1.993074 0.      ]
 [0.       0.       0.       0.489069 ... 0.959999 1.499512 2.819287 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.625182 1.431162 3.38943  0.      ]
 [0.295479 0.       0.       0.       ... 0.       1.028513 7.948227 0.      ]
 [0.       0.       0.       0.       ... 0.807668 0.202977 3.580782 0.      ]
 [0.       0.       0.       0.309345 ... 1.984916 0.173977 2.447981 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.009789 0.902895 0.      ]
 [0.       0.       0.       0.       ... 0.97585  1.608614 2.793227 0.      ]
 [0.       0.       0.       0.       ... 0.817735 0.       2.165239 0.      ]
 [0.       0.       0.       0.       ... 1.114519 0.343967 1.129258 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.898928 0.931188 1.506635 0.      ]
 [0.       0.       0.       1.25855  ... 0.       1.920579 5.767728 0.      ]
 [0.       0.       0.       1.839624 ... 0.763687 0.       4.159972 0.      ]
 [0.       0.       0.       0.       ... 1.815785 0.       2.554825 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.215551 0.       2.519837 0.      ]
 [0.       0.       0.       0.       ... 3.357724 0.       2.697538 0.      ]
 [0.       0.       0.       0.       ... 0.905896 0.382867 2.69129  0.      ]
 [0.       0.       0.       0.       ... 0.854272 0.992971 1.692043 0.      ]]
[[0.       0.       0.       0.151872 ... 0.485921 0.531537 4.446196 0.      ]
 [0.       0.       1.472445 0.       ... 1.945676 1.249109 2.862707 0.      ]
 [0.       0.       0.       0.       ... 1.790272 0.082461 1.40583  0.      ]
 [0.       0.       0.       0.       ... 0.407039 1.049338 2.333614 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.979485 0.015169 1.197373 0.      ]
 [0.       0.       0.       0.       ... 0.582815 0.       3.068586 0.      ]
 [0.       0.       0.       0.       ... 1.066291 0.235195 0.743483 0.      ]
 [0.       0.       0.       0.       ... 1.610115 0.       1.048304 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.510696 1.129355 2.899286 0.      ]
 [0.       0.       0.       0.       ... 0.201049 0.99412  3.491276 0.      ]
 [0.       0.       0.557454 0.       ... 1.497319 1.373015 2.408194 0.      ]
 [0.       0.       0.       0.       ... 1.541833 0.636379 1.340934 0.      ]]
[[0.       0.       0.       0.       ... 0.166581 0.054543 2.100481 0.      ]
 [0.       0.       0.       0.       ... 0.       0.604031 3.325325 0.      ]
 [0.       0.       0.       0.       ... 1.586018 0.       2.406504 0.      ]
 [0.       0.       0.       0.       ... 1.990965 0.551427 2.029071 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       1.910211 0.       ... 0.014939 1.326899 5.270837 0.      ]
 [0.       0.       0.       0.       ... 1.803099 1.718078 2.500473 0.      ]
 [0.       0.       0.       0.       ... 2.366262 0.625872 1.087531 0.      ]
 [0.       0.       0.       0.       ... 0.690556 1.017578 2.436644 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.646528 0.511435 2.328249 0.      ]
 [0.       0.       0.       0.       ... 1.824514 2.116812 3.367957 0.      ]
 [0.       0.       0.       0.       ... 0.564193 0.198548 2.093472 0.      ]
 [0.       0.       0.       0.       ... 1.286522 0.       4.342943 0.      ]]
[[0.       0.       0.       0.       ... 0.840771 0.741707 0.749668 0.      ]
 [0.       0.       0.10575  0.504599 ... 1.771255 0.       3.08332  0.      ]
 [0.       0.       0.       0.       ... 0.       1.926027 3.48559  0.      ]
 [0.       0.       0.       0.       ... 0.       1.587838 1.654864 0.      ]
 ...
 [0.       0.       0.       0.00844  ...

[[0.       0.       0.266698 0.270922 ... 2.947249 2.273298 3.024954 0.      ]
 [0.       0.       0.       0.       ... 1.626091 1.769946 4.644835 0.      ]
 [0.       0.       0.       0.       ... 0.501295 1.419321 2.806384 0.      ]
 [0.       0.       0.       0.       ... 1.25317  0.545778 4.104414 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.716765 0.       1.361026 0.      ]
 [0.       0.       0.       0.       ... 0.       0.591398 2.495727 0.      ]
 [0.       0.       0.       0.       ... 1.003915 0.       2.909732 0.      ]
 [0.       0.       0.       0.       ... 1.241929 0.       0.248419 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.       1.999812 0.      ]
 [0.       0.       0.       0.       ... 0.142423 0.854344 2.143654 0.      ]
 [0.       0.       0.       0.       ... 0.       0.420714 1.037064 0.      ]
 [0.       0.       0.       0.       ... 1.158663 0.260245 2.954895 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.809657 0.       1.267778 0.      ]
 [0.       0.       0.       0.       ... 1.366455 0.706885 1.863422 0.      ]
 [0.       0.       0.       0.       ... 2.034064 2.460252 3.083875 0.      ]
 [0.       0.       0.       0.       ... 0.837275 0.041261 2.352962 0.      ]
 ...
 [0.       0.       0.       0.       ... 2.186611 0.796251 2.525478 0.      ]
 [0.       0.       0.       0.       ... 0.799246 1.399874 3.211512 0.      ]
 [0.       0.       0.       0.       ... 0.316542 0.372089 2.196665 0.      ]
 [0.       0.       0.       0.460511 ... 0.       0.       4.340704 0.      ]]
[[0.       0.       0.       0.005892 ... 0.400725 0.419047 3.922597 0.      ]
 [0.       0.       0.       0.       ... 0.       1.902128 4.195979 0.      ]
 [0.       0.       0.       0.       ... 0.914659 2.407844 2.075519 0.      ]
 [0.       0.486665 0.       0.       ... 0.       1.991992 4.47877  0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.198535 0.760981 3.319623 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.468096 0.      ]
 [0.       0.       0.       0.       ... 1.069084 1.972147 2.543978 0.      ]
 [0.       0.       0.       0.       ... 0.       1.425749 0.686013 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.596465 1.414054 1.824198 0.      ]
 [0.       0.       0.       0.       ... 1.970672 1.257077 2.94743  0.      ]
 [0.       0.       0.       0.       ... 0.715039 0.       2.574452 0.      ]
 [0.       0.       0.       0.       ... 0.164011 0.       2.813527 0.      ]]
[[0.       0.       0.       0.       ... 1.598059 1.197473 3.27717  0.      ]
 [0.       0.       0.       0.       ... 0.521131 3.967899 4.859294 0.      ]
 [0.       0.       0.       0.       ... 0.406209 1.614187 2.079573 0.      ]
 [0.       0.       0.       1.565768 ... 2.105593 0.880086 3.180291 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.08289  0.       3.833273 0.      ]
 [0.       0.       0.       0.       ... 1.156045 1.126393 3.148623 0.      ]
 [0.       0.       0.       0.       ... 1.569942 1.060165 3.144804 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       4.060287 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.       0.       2.522422 0.      ]
 [0.       0.       0.       0.       ... 1.026206 0.802048 2.467839 0.      ]
 [0.       0.       2.419804 0.       ... 0.       3.94393  3.596814 0.      ]
 [0.       0.       0.       0.       ... 0.997069 0.       1.722745 0.      ]]
[[0.       0.       0.       0.       ... 0.458211 0.       1.302996 0.      ]
 [0.       0.       0.       0.       ... 1.486566 0.869155 1.273633 0.      ]
 [0.       0.       0.       0.       ... 2.047181 1.015924 1.201813 0.      ]
 [0.       0.       0.       0.       ... 0.630597 0.576608 1.579201 0.      ]
 ...
 [0.       0.       0.       0.289464 ...

[[0.       0.       0.       0.       ... 1.492799 0.432078 2.482093 0.      ]
 [0.       0.       0.       0.       ... 0.551892 0.312956 1.843961 0.      ]
 [0.       0.       0.       0.       ... 0.       1.701639 2.57901  0.      ]
 [0.       0.       0.       0.       ... 1.25379  0.       1.801004 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.026037 0.656725 2.539941 0.      ]
 [0.       0.       0.       0.       ... 0.697592 0.       1.981861 0.      ]
 [0.       0.       0.       0.       ... 1.274067 0.829875 1.750815 0.      ]
 [0.       0.       0.       0.       ... 0.984297 0.870395 1.933674 0.      ]]
[[0.       0.       0.       0.       ... 1.677302 0.       1.754724 0.      ]
 [0.       0.       0.       0.       ... 0.235905 0.706228 2.319957 0.      ]
 [0.       0.       0.       0.       ... 2.5881   0.134092 3.13217  0.      ]
 [0.       0.       0.       0.       ... 2.168476 0.117328 0.       0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.62526  0.757349 2.789312 0.      ]
 [0.       0.       0.939793 0.958778 ... 3.363203 0.       6.749949 0.      ]
 [0.       0.       0.       1.019459 ... 1.70772  1.773905 3.147331 0.      ]
 [0.       0.       0.       0.       ... 1.078679 0.268866 3.941347 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.793235 1.421023 1.486079 0.      ]
 [0.       0.       0.       0.       ... 2.792961 0.       2.243258 0.      ]
 [0.       0.       0.       0.       ... 0.418555 0.       4.002435 0.      ]
 [0.       0.       0.       0.       ... 0.829073 0.238634 1.458106 0.      ]]
[[0.       0.       0.       0.393525 ... 0.72364  0.623572 2.494404 0.      ]
 [0.       0.       0.       0.       ... 0.783304 0.53711  1.338399 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       2.313951 0.      ]
 [0.       0.       0.       0.       ... 1.787175 1.180133 3.285639 0.      ]
 ...
 [0.       0.       0.       0.842941 ...

[[0.       0.       0.       0.       ... 1.745092 0.853558 3.351456 0.      ]
 [0.       0.       0.       0.       ... 2.110469 1.482902 3.952565 0.      ]
 [0.       0.       0.       0.       ... 0.099542 0.034163 2.323953 0.      ]
 [0.       0.       0.783063 2.32287  ... 0.42717  1.765369 5.672672 0.      ]
 ...
 [0.       0.       0.       0.       ... 2.762793 1.1889   2.419988 0.      ]
 [0.       0.       1.05515  0.       ... 1.306486 0.039168 4.37355  0.      ]
 [0.       0.       0.       0.       ... 0.       0.810627 2.429068 0.      ]
 [0.       0.       0.       0.       ... 0.185402 0.607754 1.238208 0.      ]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 2.255335e+00 0.000000e+00 1.629380e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 9.322189e-01 0.000000e+00 5.644325e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 2.456336e+00 6.674924e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 2

[[0.       0.       0.       0.       ... 0.085345 1.539776 1.43568  0.      ]
 [0.       0.       0.       0.       ... 1.144984 0.440889 2.669962 0.      ]
 [0.       0.       0.       0.       ... 0.21432  2.18409  2.355615 0.      ]
 [0.       0.       0.       0.       ... 0.935912 0.       2.361888 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.931131 0.278384 2.806091 0.      ]
 [0.       0.       0.       0.       ... 1.399063 0.706314 1.321004 0.      ]
 [0.       0.       0.       1.451277 ... 2.728017 1.184403 3.030821 0.      ]
 [0.       0.       0.       0.       ... 0.841771 0.714856 2.0997   0.      ]]
[[0.       0.       0.       0.80029  ... 1.153992 0.       3.054691 0.      ]
 [0.       0.       0.       0.       ... 0.977215 0.150976 2.787605 0.      ]
 [0.       0.       0.       0.       ... 0.       1.524894 2.471194 0.      ]
 [0.       0.       0.       0.       ... 0.760173 1.690841 3.768917 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.       0.       1.933897 0.      ]
 [0.       0.       0.       0.       ... 1.767899 2.093015 4.197497 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       0.238294 0.      ]
 [0.       0.       0.       0.       ... 0.449571 1.716685 1.137547 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.141823 0.451192 3.163332 0.      ]
 [0.       0.       0.       0.       ... 1.356467 1.188379 3.180156 0.      ]
 [0.       0.234933 0.       0.       ... 2.707442 0.       3.431836 0.      ]
 [0.       0.       0.       0.       ... 2.421281 0.       0.907011 0.      ]]
[[0.       0.       0.       0.       ... 1.800673 0.       2.307681 0.      ]
 [0.       0.       0.       0.       ... 1.60298  0.       0.234718 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       2.630038 0.      ]
 [0.       0.       0.       0.       ... 0.       0.706705 5.082873 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.212464 0.       ... 3.037263 0.908243 0.       0.      ]
 [0.       0.       0.       0.       ... 0.615086 0.       3.130255 0.      ]
 [0.       0.       1.471516 0.       ... 0.       0.240548 4.012052 0.      ]
 [0.       0.       0.       0.       ... 3.436159 1.452033 3.845674 0.924523]
 ...
 [0.       0.       0.       0.754414 ... 0.       0.987612 5.777651 0.      ]
 [0.       0.       0.       0.       ... 1.865685 0.       0.       0.      ]
 [0.       0.       0.       0.       ... 2.522273 0.942753 3.723417 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.695059 0.      ]]
[[0.       0.       0.       0.       ... 0.118312 0.008404 1.319531 0.      ]
 [0.       0.       0.       0.       ... 1.043154 0.188105 2.045075 0.      ]
 [0.       0.       0.       0.       ... 1.595085 0.778566 0.82564  0.      ]
 [0.       0.       0.       0.       ... 1.249251 0.612076 2.445907 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.392245 0.426467 2.868529 0.      ]
 [0.       0.       0.       0.       ... 0.465914 1.521064 1.104465 0.      ]
 [0.       0.       0.       0.       ... 1.586786 0.44341  3.209564 0.      ]
 [0.       0.       0.       0.       ... 1.610935 0.       0.       0.      ]
 ...
 [0.       0.       2.530616 0.470482 ... 0.       1.229771 4.232831 0.      ]
 [0.       0.       0.       0.       ... 1.069783 0.835898 4.28721  0.      ]
 [0.       0.       0.       0.       ... 0.609107 1.445999 3.589547 0.      ]
 [0.       0.       2.638849 0.       ... 0.055723 1.297782 4.168519 0.      ]]
[[0.       0.       0.       0.       ... 0.       0.387472 1.777697 0.      ]
 [0.       0.       0.       0.       ... 0.312047 0.       0.76978  0.      ]
 [0.       0.       0.       0.       ... 2.604032 0.385037 4.23891  0.      ]
 [0.       0.       0.       0.       ... 0.123148 0.691758 2.91366  0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.748905 0.       2.204466 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       0.       0.      ]
 [0.       0.       0.       0.       ... 0.514136 0.       3.916066 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       1.439637 0.      ]
 ...
 [0.       0.       0.       0.678301 ... 0.       0.048019 1.861587 0.      ]
 [0.       0.       1.385466 0.       ... 0.       4.261202 6.154233 0.      ]
 [0.       1.176477 0.513137 0.       ... 3.264215 1.355969 5.224872 0.      ]
 [0.       0.       0.       0.       ... 0.       1.714822 4.285303 0.      ]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.516138e+00 2.933085e-03 2.494987e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 3.143905e-01 6.115865e-01 1.789530e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 7.351298e-01 3.137011e-01 2.131513e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0

[[0.       0.       0.       0.       ... 0.       0.       2.062117 0.      ]
 [0.       0.       0.       1.745001 ... 0.       2.726528 5.471253 0.      ]
 [0.       0.       0.       0.       ... 0.357952 0.829229 2.172477 0.      ]
 [0.       0.       0.       0.       ... 0.249771 0.653545 3.505336 0.      ]
 ...
 [0.       0.       0.       0.       ... 2.174406 1.361727 1.809968 0.      ]
 [0.       0.       0.       2.519191 ... 0.       1.563161 6.178398 0.      ]
 [0.       0.       0.       0.       ... 1.429175 0.119439 2.899893 0.      ]
 [0.       0.       0.       0.       ... 2.141976 0.       2.948967 0.      ]]
[[0.       0.       0.       0.       ... 2.06488  0.875987 3.294425 0.      ]
 [0.       0.       0.       0.       ... 2.293876 0.992863 0.523726 0.      ]
 [0.       0.       0.       0.       ... 1.315223 0.134444 1.813868 0.      ]
 [0.       0.       0.       2.443383 ... 0.       1.313904 3.957581 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.545016 0.544271 1.613018 0.      ]
 [0.       0.       0.       1.954201 ... 1.255735 0.       4.812264 0.      ]
 [0.       0.       0.       0.       ... 0.       0.467332 1.743627 0.      ]
 [0.       0.       0.       0.       ... 1.494034 0.052827 4.270334 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.738504 0.       1.470962 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.189222 0.      ]
 [0.       0.       0.884023 0.       ... 0.       2.660636 5.571019 0.      ]
 [0.       0.       0.       0.       ... 1.001649 0.       1.720743 0.      ]]
[[0.       0.       0.       0.       ... 0.90812  0.       1.332022 0.      ]
 [0.       0.       0.       0.       ... 1.39031  1.077904 2.546254 0.      ]
 [0.       0.       0.       0.       ... 0.756509 0.       4.603075 0.      ]
 [0.       0.       0.       0.       ... 0.754345 0.       2.090691 0.      ]
 ...
 [0.       0.       0.       0.754393 ...

[[0.       0.       0.       0.       ... 1.053829 0.       0.81962  0.      ]
 [0.       0.       0.       0.       ... 1.969337 0.       0.93675  0.      ]
 [0.       0.       0.       0.       ... 0.       0.614245 3.822706 0.      ]
 [0.       0.       0.       0.       ... 1.330209 0.853166 2.041119 0.      ]
 ...
 [0.       0.       0.       0.       ... 1.39439  0.761447 5.230814 0.      ]
 [0.       0.       0.       0.       ... 2.258284 1.44069  2.035291 0.      ]
 [0.       0.       0.       0.       ... 1.296659 0.038689 3.786339 0.      ]
 [0.       0.       0.       0.       ... 0.       1.693019 4.114963 0.      ]]
[[0.       0.       0.090428 0.       ... 0.       0.       1.309133 0.      ]
 [0.       0.       0.       0.       ... 2.069835 0.       3.816656 0.      ]
 [0.       0.       1.182982 0.       ... 1.777665 0.       3.412388 0.      ]
 [0.       0.       0.       0.       ... 0.086284 0.       2.63419  0.      ]
 ...
 [0.       0.       0.935385 0.       ...

[[0.       0.       0.       0.       ... 0.778271 0.771928 1.908168 0.      ]
 [0.       0.       0.       0.       ... 1.058267 1.813798 1.007641 0.      ]
 [0.       0.       0.       0.       ... 0.189103 0.640406 0.       0.      ]
 [0.       0.       0.349197 0.       ... 1.306529 0.034484 3.892713 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.       0.928923 3.156554 0.      ]
 [0.       0.       0.       0.       ... 1.524794 0.600051 2.169755 0.      ]
 [0.       0.       0.       0.       ... 2.204138 0.858473 1.848819 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       3.536864 0.      ]]
[[0.       0.       0.       0.726197 ... 1.224874 0.       4.000624 0.      ]
 [0.       0.       0.       0.       ... 1.342352 0.       0.630689 0.      ]
 [0.       0.       0.       0.       ... 1.102929 0.       1.102798 0.      ]
 [0.       0.       0.       0.486458 ... 2.453665 0.       1.564339 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 0.959124 0.425499 3.744258 0.      ]
 [0.       0.       0.       0.       ... 2.201038 0.419982 2.238395 0.      ]
 [0.       0.       0.       0.       ... 1.086936 0.       2.11471  0.      ]
 [0.       0.       0.       0.       ... 0.       1.858392 3.377299 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.217539 0.689918 1.646003 0.      ]
 [0.       0.       0.       0.       ... 0.929118 0.       1.455974 0.      ]
 [0.       0.       0.       0.       ... 1.338528 1.178268 2.884228 0.      ]
 [0.       0.       0.       0.       ... 0.602439 0.372005 2.359123 0.      ]]
[[0.       0.       0.       0.       ... 1.010764 0.       0.991424 0.      ]
 [0.       0.       0.       0.       ... 1.233499 0.       4.516732 0.      ]
 [0.       0.       0.55633  0.28795  ... 0.       2.007897 6.795907 0.      ]
 [0.       0.       0.       0.       ... 0.81266  0.382278 1.844539 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.287576 1.481248 5.791582 0.      ]
 [0.       0.       0.       0.       ... 0.444488 0.802386 1.654164 0.      ]
 [0.       0.       0.       0.       ... 1.805666 0.943473 1.200599 0.      ]
 [0.       0.       0.       0.       ... 0.       0.318388 2.486302 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.       0.       0.310067 0.      ]
 [0.       0.       0.       0.       ... 0.621879 0.644819 1.660804 0.      ]
 [0.       0.       0.       0.       ... 2.51728  1.986589 3.393995 0.      ]
 [0.       0.       0.       0.       ... 0.2886   0.       3.105321 0.      ]]
[[0.       0.       0.       0.       ... 1.145242 1.854213 3.760531 0.      ]
 [0.       0.       1.298624 0.       ... 2.043348 0.32264  4.743244 0.      ]
 [0.       0.       0.       0.       ... 1.341541 0.       2.801053 0.      ]
 [0.       0.       0.       0.       ... 1.101679 0.085507 1.391152 0.      ]
 ...
 [0.       0.       0.       0.       ...

[[0.       0.       0.       0.       ... 1.858243 1.192365 3.540623 0.      ]
 [0.       0.       0.       0.       ... 1.957129 0.162734 3.632126 0.      ]
 [0.       0.       0.       0.       ... 0.450612 0.919913 2.89107  0.      ]
 [0.       0.       0.       0.       ... 0.       2.569505 5.513924 0.      ]
 ...
 [0.       0.       0.       0.       ... 0.744169 0.924275 2.243245 0.      ]
 [0.       0.       0.       0.       ... 0.       0.       2.412526 0.      ]
 [0.       0.       0.670705 0.       ... 0.       0.       4.61536  0.      ]
 [0.       0.       0.       0.       ... 1.867355 1.469337 3.113851 0.      ]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 1.081680e+00 8.570337e-01 1.876792e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 6.097931e-01 0.000000e+00 4.004129e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 0.000000e+00 1.696113e+00 0.000000e+00]
 [2.511263e-03 0.000000e+00 0

In [69]:
df = pd.DataFrame(img_vecs.items(), columns=['img_id', 'img_vec'])

In [70]:
df.head()

img_id  \
0  /home/sloth/Desktop/animeface/animeface-2009/a...   
1  /home/sloth/Desktop/animeface/animeface-2009/a...   
2  /home/sloth/Desktop/animeface/animeface-2009/a...   
3  /home/sloth/Desktop/animeface/animeface-2009/a...   
4  /home/sloth/Desktop/animeface/animeface-2009/a...   

                                             img_vec  
0  [0.0, 0.0, 0.0, 0.0, 0.06119205057621002, 2.48...  
1  [0.0, 0.0, 0.0, 0.0, 0.7806511521339417, 1.550...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 3.345784902572632, 0...  
3  [0.0, 0.0, 0.0, 0.0, 0.44981351494789124, 1.80...  
4  [0.0, 0.0, 0.0, 0.08110424876213074, 0.5474264...

In [71]:
df.to_csv("img_feature_vecs_3.csv",index=False)